name: Deploy static content to Pages

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
    
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python script
        working-directory: updater/ # Execute script from the 'updater/' directory
        run: python3 update.py update
      
      # Upload the modified site as an artifact (named 'github-pages')
      - name: Upload modified site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: './site/'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
